"""TTS (Text-to-Speech) routes – powered by the ElevenLabs API."""

import logging

import fastapi
from fastapi.responses import Response
from pydantic import BaseModel, Field

from src.api.dependencies.auth import get_current_user
from src.services.elevenlabs_tts import generate_tts_audio

router = fastapi.APIRouter(prefix="/tts", tags=["tts"])
logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Request / Response schemas
# ---------------------------------------------------------------------------


class TTSRequest(BaseModel):
    text: str = Field(
        ...,
        min_length=1,
        max_length=5_000,
        description="Text to convert to speech (max 5 000 characters).",
        examples=["Hello, welcome to Samvaad Sathi!"],
    )
    voice_id: str | None = Field(
        default=None,
        description=(
            "Optional ElevenLabs voice ID. "
            "Defaults to the ELEVENLABS_VOICE_ID setting when omitted."
        ),
        examples=["JBFqnCBsd6RMkjVDRTpX"],
    )


# ---------------------------------------------------------------------------
# Endpoint
# ---------------------------------------------------------------------------


@router.post(
    path="/convert",
    name="tts:convert",
    status_code=fastapi.status.HTTP_200_OK,
    summary="Convert text to speech via ElevenLabs",
    description=(
        "Accepts a text payload and returns an MP3 audio file generated by the "
        "ElevenLabs text-to-speech API. "
        "Requires a valid Bearer token. "
        "Max input length is 5 000 characters."
    ),
    response_class=Response,
    responses={
        200: {
            "content": {"audio/mpeg": {}},
            "description": "MP3 audio file of the synthesised speech.",
        },
        400: {"description": "Bad request – e.g. empty text."},
        503: {"description": "ElevenLabs service unavailable or not configured."},
    },
)
async def convert_text_to_speech(
    payload: TTSRequest,
    current_user=fastapi.Depends(get_current_user),
) -> Response:
    """
    Converts ``payload.text`` to speech using ElevenLabs and streams back an
    MP3 file directly.
    """
    audio_bytes, error, latency_ms = await generate_tts_audio(
        text=payload.text,
        voice_id=payload.voice_id,
    )

    if error:
        status = (
            fastapi.status.HTTP_503_SERVICE_UNAVAILABLE
            if "not configured" in error or "not installed" in error
            else fastapi.status.HTTP_502_BAD_GATEWAY
        )
        raise fastapi.HTTPException(status_code=status, detail=error)

    logger.info(
        "TTS convert: user=%s chars=%d latency=%dms",
        current_user.id,
        len(payload.text),
        latency_ms,
    )

    return Response(
        content=audio_bytes,
        media_type="audio/mpeg",
        headers={
            "X-Latency-Ms": str(latency_ms),
            "Content-Disposition": 'attachment; filename="tts_output.mp3"',
        },
    )
