"""add interview_question table and question_id to question_attempt

Revision ID: e4792e2a1b7c
Revises: 0ab50c01c7d7
Create Date: 2025-09-15 23:58:43.616272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4792e2a1b7c'
down_revision = '0ab50c01c7d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('topic', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interview.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_question_interview_id'), 'interview_question', ['interview_id'], unique=False)
    op.create_index(op.f('ix_interview_question_order'), 'interview_question', ['order'], unique=False)
    op.create_index(op.f('ix_interview_question_status'), 'interview_question', ['status'], unique=False)
    op.add_column('question_attempt', sa.Column('question_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_question_attempt_question_id'), 'question_attempt', ['question_id'], unique=False)
    op.create_foreign_key(None, 'question_attempt', 'interview_question', ['question_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question_attempt', type_='foreignkey')
    op.drop_index(op.f('ix_question_attempt_question_id'), table_name='question_attempt')
    op.drop_column('question_attempt', 'question_id')
    op.drop_index(op.f('ix_interview_question_status'), table_name='interview_question')
    op.drop_index(op.f('ix_interview_question_order'), table_name='interview_question')
    op.drop_index(op.f('ix_interview_question_interview_id'), table_name='interview_question')
    op.drop_table('interview_question')
    # ### end Alembic commands ###
