"""add_resume_used_to_interview_question

Revision ID: 38befcec7635
Revises: 1f2e3d4c5b6a
Create Date: 2025-09-28 14:22:38.740442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38befcec7635'
down_revision = '1f2e3d4c5b6a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_question', sa.Column('resume_used', sa.Boolean(), nullable=False, server_default='false'))
    op.create_index(op.f('ix_interview_question_resume_used'), 'interview_question', ['resume_used'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_question_resume_used'), table_name='interview_question')
    op.drop_column('interview_question', 'resume_used')
    # ### end Alembic commands ###
