"""add_category_to_interview_question

Revision ID: 5152c4336536
Revises: 38befcec7635
Create Date: 2025-09-28 19:54:30.575251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5152c4336536'
down_revision = '38befcec7635'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_question', sa.Column('category', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_question', 'category')
    # ### end Alembic commands ###
