"""Added user profiling attributes to user's table

Revision ID: 0ab50c01c7d7
Revises: 5cb484ca39a5
Create Date: 2025-09-14 15:11:05.855022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ab50c01c7d7'
down_revision = '5cb484ca39a5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
