"""add_unique_constraint_on_user_id_and_file_sha256

Revision ID: 973b34efacf4
Revises: 51830b659a3f
Create Date: 2026-09-07 16:45:35.466465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '973b34efacf4'
down_revision = '51830b659a3f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_resume_user_sha256', 'user_resume', ['user_id', 'file_sha256'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_resume_user_sha256', 'user_resume', type_='unique')
    # ### end Alembic commands ###
