"""add_job_profile_id_to_interview

Revision ID: eb6095fa9ae8
Revises: 26d2da3d9530
Create Date: 2026-08-18 19:26:52.812139

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eb6095fa9ae8'
down_revision = '26d2da3d9530'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview', sa.Column('job_profile_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_interview_job_profile_id'), 'interview', ['job_profile_id'], unique=False)
    op.create_foreign_key('fk_interview_job_profile_id', 'interview', 'job_profile', ['job_profile_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_interview_job_profile_id', 'interview', type_='foreignkey')
    op.drop_index(op.f('ix_interview_job_profile_id'), table_name='interview')
    op.drop_column('interview', 'job_profile_id')
    # ### end Alembic commands ###
