"""Add nice-to-have columns and CHECK constraint to UserResume

Revision ID: 4ec10d24bb88
Revises: 3fab3fb64c85
Create Date: 2026-09-07 15:11:50.455857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ec10d24bb88'
down_revision = '3fab3fb64c85'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_resume', sa.Column('content_type', sa.String(length=128), nullable=True))
    op.add_column('user_resume', sa.Column('size_bytes', sa.Integer(), nullable=True))
    op.add_column('user_resume', sa.Column('file_sha256', sa.String(length=64), nullable=True))
    op.create_check_constraint(
        'chk_user_resume_source',
        'user_resume',
        "source IN ('onboarding', 'ats_final')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chk_user_resume_source', 'user_resume', type_='check')
    op.drop_column('user_resume', 'file_sha256')
    op.drop_column('user_resume', 'size_bytes')
    op.drop_column('user_resume', 'content_type')
    # ### end Alembic commands ###
