"""Add composite index on user_id and created_at to UserResume

Revision ID: 51830b659a3f
Revises: 4ec10d24bb88
Create Date: 2026-09-07 15:22:20.907002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51830b659a3f'
down_revision = '4ec10d24bb88'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_user_resume_user_id_created_at', 'user_resume', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_resume_user_id_created_at', table_name='user_resume')
    # ### end Alembic commands ###
