"""add_original_resume_s3_key

Revision ID: 02694da2851a
Revises: 69e6a13d9f75
Create Date: 2026-09-03 08:40:14.943710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02694da2851a'
down_revision = '69e6a13d9f75'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('original_resume_s3_key', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'original_resume_s3_key')
    # ### end Alembic commands ###
