"""add ai resume analysis table

Revision ID: 95d25f35a7f6
Revises: job_profile_001
Create Date: 2026-05-27 14:46:39.716644

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '95d25f35a7f6'
down_revision = 'job_profile_001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_structure_practice_answer_practice_id'), table_name='structure_practice_answer')
    op.drop_index(op.f('ix_structure_practice_answer_question_index'), table_name='structure_practice_answer')
    op.drop_table('structure_practice_answer')
    op.drop_index(op.f('ix_pronunciation_practice_created_at'), table_name='pronunciation_practice')
    op.drop_index(op.f('ix_pronunciation_practice_user_id'), table_name='pronunciation_practice')
    op.drop_table('pronunciation_practice')
    op.drop_index(op.f('ix_structure_practice_interview_id'), table_name='structure_practice')
    op.drop_index(op.f('ix_structure_practice_status'), table_name='structure_practice')
    op.drop_index(op.f('ix_structure_practice_track'), table_name='structure_practice')
    op.drop_index(op.f('ix_structure_practice_user_id'), table_name='structure_practice')
    op.drop_table('structure_practice')
    op.alter_column('interview', 'difficulty',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_interview_difficulty'), 'interview', ['difficulty'], unique=False)
    op.drop_index(op.f('ix_pacing_practice_session_user_level'), table_name='pacing_practice_session')
    op.drop_constraint(op.f('question_supplement_interview_question_id_key'), 'question_supplement', type_='unique')
    op.drop_index(op.f('ix_question_supplement_interview_question_id'), table_name='question_supplement')
    op.create_index(op.f('ix_question_supplement_interview_question_id'), 'question_supplement', ['interview_question_id'], unique=True)
    op.drop_index(op.f('ix_report_interview_id'), table_name='report')
    op.create_index(op.f('ix_report_interview_id'), 'report', ['interview_id'], unique=True)
    op.drop_index(op.f('ix_session_token'), table_name='session')
    op.create_unique_constraint(None, 'session', ['token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'session', type_='unique')
    op.create_index(op.f('ix_session_token'), 'session', ['token'], unique=True)
    op.drop_index(op.f('ix_report_interview_id'), table_name='report')
    op.create_index(op.f('ix_report_interview_id'), 'report', ['interview_id'], unique=False)
    op.drop_index(op.f('ix_question_supplement_interview_question_id'), table_name='question_supplement')
    op.create_index(op.f('ix_question_supplement_interview_question_id'), 'question_supplement', ['interview_question_id'], unique=False)
    op.create_unique_constraint(op.f('question_supplement_interview_question_id_key'), 'question_supplement', ['interview_question_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_pacing_practice_session_user_level'), 'pacing_practice_session', ['user_id', 'level'], unique=False)
    op.drop_index(op.f('ix_interview_difficulty'), table_name='interview')
    op.alter_column('interview', 'difficulty',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_table('structure_practice',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('interview_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('track', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interview.id'], name=op.f('structure_practice_interview_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('structure_practice_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('structure_practice_pkey'))
    )
    op.create_index(op.f('ix_structure_practice_user_id'), 'structure_practice', ['user_id'], unique=False)
    op.create_index(op.f('ix_structure_practice_track'), 'structure_practice', ['track'], unique=False)
    op.create_index(op.f('ix_structure_practice_status'), 'structure_practice', ['status'], unique=False)
    op.create_index(op.f('ix_structure_practice_interview_id'), 'structure_practice', ['interview_id'], unique=False)
    op.create_table('pronunciation_practice',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('difficulty', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('words', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('pronunciation_practice_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pronunciation_practice_pkey'))
    )
    op.create_index(op.f('ix_pronunciation_practice_user_id'), 'pronunciation_practice', ['user_id'], unique=False)
    op.create_index(op.f('ix_pronunciation_practice_created_at'), 'pronunciation_practice', ['created_at'], unique=False)
    op.create_table('structure_practice_answer',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('practice_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('answer_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('time_spent_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('analysis_result', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('analyzed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('section_name', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['practice_id'], ['structure_practice.id'], name=op.f('structure_practice_answer_practice_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('structure_practice_answer_pkey'))
    )
    op.create_index(op.f('ix_structure_practice_answer_question_index'), 'structure_practice_answer', ['question_index'], unique=False)
    op.create_index(op.f('ix_structure_practice_answer_practice_id'), 'structure_practice_answer', ['practice_id'], unique=False)
    # ### end Alembic commands ###
