"""Add audio_url to questions

Revision ID: 69e6a13d9f75
Revises: eb6095fa9ae8
Create Date: 2026-09-02 12:03:32.633404

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '69e6a13d9f75'
down_revision = 'eb6095fa9ae8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_question', sa.Column('audio_url', sa.String(length=512), nullable=True))
    op.add_column('job_profile_question', sa.Column('audio_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_profile_question', 'audio_url')
    op.drop_column('interview_question', 'audio_url')
    # ### end Alembic commands ###
