"""add_user_resume_instances_table

Revision ID: 988853ec372d
Revises: 231b7830518d
Create Date: 2026-06-04 07:50:49.308459

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '988853ec372d'
down_revision = '231b7830518d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_resume_instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.String(length=64), server_default='default_ats_001', nullable=False),
    sa.Column('resume_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='DRAFT', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_resume_instances_user_id'), 'user_resume_instances', ['user_id'], unique=False)
    op.drop_index(op.f('ix_generated_resumes_analysis_id'), table_name='generated_resumes')
    op.drop_index(op.f('ix_generated_resumes_generated_resume_id'), table_name='generated_resumes')
    op.drop_index(op.f('ix_generated_resumes_user_id'), table_name='generated_resumes')
    op.drop_table('generated_resumes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('generated_resumes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('generated_resume_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('analysis_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('template_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('optimized_resume_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('pdf_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('generated_resumes_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('generated_resumes_pkey'))
    )
    op.create_index(op.f('ix_generated_resumes_user_id'), 'generated_resumes', ['user_id'], unique=False)
    op.create_index(op.f('ix_generated_resumes_generated_resume_id'), 'generated_resumes', ['generated_resume_id'], unique=True)
    op.create_index(op.f('ix_generated_resumes_analysis_id'), 'generated_resumes', ['analysis_id'], unique=False)
    op.drop_index(op.f('ix_user_resume_instances_user_id'), table_name='user_resume_instances')
    op.drop_table('user_resume_instances')
    # ### end Alembic commands ###
