"""Add audio_url to questions

Revision ID: 69e6a13d9f75
Revises: eb6095fa9ae8
Create Date: 2026-09-02 12:03:32.633404

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '69e6a13d9f75'
down_revision = 'eb6095fa9ae8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_structure_practice_answer_practice_id'), table_name='structure_practice_answer')
    op.drop_index(op.f('ix_structure_practice_answer_question_index'), table_name='structure_practice_answer')
    op.drop_table('structure_practice_answer')
    op.drop_index(op.f('ix_structure_practice_interview_id'), table_name='structure_practice')
    op.drop_index(op.f('ix_structure_practice_status'), table_name='structure_practice')
    op.drop_index(op.f('ix_structure_practice_track'), table_name='structure_practice')
    op.drop_index(op.f('ix_structure_practice_user_id'), table_name='structure_practice')
    op.drop_table('structure_practice')
    op.drop_index(op.f('ix_pronunciation_practice_difficulty'), table_name='pronunciation_practice')
    op.drop_index(op.f('ix_pronunciation_practice_status'), table_name='pronunciation_practice')
    op.drop_index(op.f('ix_pronunciation_practice_user_id'), table_name='pronunciation_practice')
    op.drop_table('pronunciation_practice')
    op.add_column('interview_question', sa.Column('audio_url', sa.String(length=512), nullable=True))
    op.alter_column('job_profile', 'category',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=160),
               existing_nullable=True)
    op.alter_column('job_profile', 'employment_type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.execute("UPDATE job_profile SET status = 'active' WHERE status IS NULL")
    op.alter_column('job_profile', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=32),
               nullable=False)
    op.add_column('job_profile_question', sa.Column('audio_url', sa.String(length=512), nullable=True))
    op.create_unique_constraint('uq_user_student_id', 'user', ['student_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_student_id', 'user', type_='unique')
    op.drop_column('job_profile_question', 'audio_url')
    op.alter_column('job_profile', 'status',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('job_profile', 'employment_type',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('job_profile', 'category',
               existing_type=sa.String(length=160),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('interview_question', 'audio_url')
    op.create_table('pronunciation_practice',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('difficulty', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('words', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('pronunciation_practice_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pronunciation_practice_pkey'))
    )
    op.create_index(op.f('ix_pronunciation_practice_user_id'), 'pronunciation_practice', ['user_id'], unique=False)
    op.create_index(op.f('ix_pronunciation_practice_status'), 'pronunciation_practice', ['status'], unique=False)
    op.create_index(op.f('ix_pronunciation_practice_difficulty'), 'pronunciation_practice', ['difficulty'], unique=False)
    op.create_table('structure_practice_answer',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('practice_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('section_name', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('answer_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('time_spent_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('analysis_result', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('analyzed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['practice_id'], ['structure_practice.id'], name=op.f('structure_practice_answer_practice_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('structure_practice_answer_pkey'))
    )
    op.create_index(op.f('ix_structure_practice_answer_question_index'), 'structure_practice_answer', ['question_index'], unique=False)
    op.create_index(op.f('ix_structure_practice_answer_practice_id'), 'structure_practice_answer', ['practice_id'], unique=False)
    op.create_table('structure_practice',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('interview_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('track', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('questions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['interview_id'], ['interview.id'], name=op.f('structure_practice_interview_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('structure_practice_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('structure_practice_pkey'))
    )
    op.create_index(op.f('ix_structure_practice_user_id'), 'structure_practice', ['user_id'], unique=False)
    op.create_index(op.f('ix_structure_practice_track'), 'structure_practice', ['track'], unique=False)
    op.create_index(op.f('ix_structure_practice_status'), 'structure_practice', ['status'], unique=False)
    op.create_index(op.f('ix_structure_practice_interview_id'), 'structure_practice', ['interview_id'], unique=False)
    # ### end Alembic commands ###
